name: Send Marvel Rival Stats to TRMNL
env:
  api_key: ${{ secrets.MARVELRIVALSAPIKEY }}
  trmnl_plugin_id1: ${{ secrets.TRMNL_PLUGIN_ID1 }}
  trmnl_plugin_id2: ${{ secrets.TRMNL_PLUGIN_ID2 }}
  username1: ${{ vars.USERNAME1 }}
  username2: ${{ vars.USERNAME2  }}
on: 
  schedule:
  - cron: '0 0 * * *'
  - cron: '0 2 * * *'
  - cron: '0 4 * * *'
  - cron: '0 6 * * *'
  - cron: '0 8 * * *'
  workflow_dispatch:
jobs:     
  run-script:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run PowerShell script for user 1
      if: ${{ env.trmnl_plugin_id1 && env.username1 }}
      run: .\scripts\MarvelRivalsTrmnl.ps1 -TrmnlPluginId "$env:trmnl_plugin_id1" -APIKey "$env:api_key" -username "$env:username1" > $null
      shell: pwsh
      
    - name: Sleep for 10 minutes
      run: Start-Sleep -s 600
      shell: pwsh

    - name: Run PowerShell script for user 2
      if: ${{ env.trmnl_plugin_id2 && env.username2 }}
      run: .\scripts\MarvelRivalsTrmnl.ps1 -TrmnlPluginId "$env:trmnl_plugin_id2" -APIKey "$env:api_key" -username "$env:username2" > $null
      shell: pwsh
